using UnityEngine;
using System.Collections.Generic;
using System.Collections;

public class item_controll : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        Collider2D c;
        if (!GetComponent<Collider2D>())
        {
            c = gameObject.AddComponent<BoxCollider2D>();
        }
        else
        {
            c = GetComponent<Collider2D>();
        }
        c.isTrigger = true;

    }
    void OnTriggerEnter2D(Collider2D other)
    {
        Destroy(gameObject);
    }
    // Update is called once per frame
    void Update()
    {

    }
}
